import test from 'node:test';
import assert from 'node:assert/strict';
import { jobFromNative } from '../../tools/translation-exchange/native-export.mjs';
import { prepareReview } from '../../tools/translation-exchange/native-review.mjs';
import { buildApplyPlan } from '../../tools/translation-exchange/native-apply.mjs';
import { HEADERS,exportRows } from '../../tools/translation-exchange/exchange.mjs';
const request=()=>({database:'flashterm-dev',filePath:'file:/Disk/Test/flashterm-dev.fmp12',jobId:'1491ea8c-6438-4d40-8bf9-a43548976688',selectedIds:'12',source:'de-DE',target:'en-US',languages:'de-DE\ren-US',terms:[['22','12','de-DE','Pilz','2','11','0','',''],['23','12','en-US','fungus','2','11','0','',''],['24','12','en-US','mushroom','1','11','0','','']].map(r=>r.join('␟')).join('␞'),definitions:[['12','de-DE','Ein Pilz.','11',''],['12','en-US','Old definition.','11','']].map(r=>r.join('␟')).join('␞')});
function fixture(){const r=request();const {job}=jobFromNative(r);const rows=exportRows(job);rows[1][9]='New definition.';rows[1][10]='Fertig';return {r,p:prepareReview(job,[HEADERS,...rows],r.database,r.filePath),id:job.rows[1].rowId};}
test('selected definition updates canonical text and all active derived terms',()=>{const {r,p,id}=fixture(),before=JSON.stringify(r);const plan=buildApplyPlan(p,r,[id]);assert.equal(plan.changes.length,1);assert.deepEqual(plan.operations.map(o=>o.table),['AT_Definition','AT_Term','AT_Term']);assert.equal(plan.locks.length,6);assert.equal(JSON.stringify(r),before);assert.equal(plan.databaseChanged,false);});
test('partial approval cannot import pending, duplicate or unknown positions',()=>{const {r,p,id}=fixture();assert.throws(()=>buildApplyPlan(p,r,[p.job.rows[0].rowId]),/gesperrt/);assert.throws(()=>buildApplyPlan(p,r,[id,id]),/unterschiedliche/);assert.throws(()=>buildApplyPlan(p,r,['foreign']),/gesperrt/);assert.throws(()=>buildApplyPlan(p,r,[]),/auswählen/);});
test('approval rechecks concurrent source and target changes',()=>{const {r,p,id}=fixture();for(const changed of [{...r,definitions:r.definitions.replace('Old definition.','Concurrent edit.')},{...r,terms:r.terms.replace('Pilz','Neuer Pilz')}])assert.throws(()=>buildApplyPlan(p,changed,[id]),/gesperrt/);});
test('repeated approval produces no writes after identical import',()=>{const {r,p,id}=fixture();const plan=buildApplyPlan(p,{...r,definitions:r.definitions.replace('Old definition.','New definition.')},[id]);assert.equal(plan.operations.length,0);assert.equal(plan.changes.length,0);assert.equal(plan.unchanged,1);});
test('creating an unverified new native record is blocked',()=>{const r=request();r.definitions=r.definitions.split('␞')[0];const {job}=jobFromNative(r);const rows=exportRows(job);rows[1][9]='New definition.';rows[1][10]='Fertig';const p=prepareReview(job,[HEADERS,...rows],r.database,r.filePath);assert.throws(()=>buildApplyPlan(p,r,[job.rows[1].rowId]),/neue Definition/);});
